### ISSUE TITLE
Working around the WP-Engine cache

### ISSUE THREAD

**Issue by alaninteractive** [yellowtree/wp-geoip-detect#18] opened 2015-07-15 01:29 UTC
Hi. Loving the plugin, but do you have any suggestions for working around aggressive server-side caching (WPEngine)? 

Thanks

**Comment by benjaminpick** [comment] 2015-07-15 18:55
After reading a bit on WPEngine they seem quite aggressive in caching
indeed. The way they'd recommend is getting the geo-location bits via
AJAX (thus uncached - right? Probably). I could create an interface for
this (basically returning the result of
geoip_detect2_get_info_from_current_ip as JSON data) but you still have
to treat this data via JS instead of PHP.

You may also be able to let them configure which pages they shouldn't
cache via support ticket. 

On 15.07.2015 03:29, Alan Bauchop wrote:
>
> Hi. Loving the plugin, but do you have any suggestions for working
> around aggressive server-side caching (WPEngine)?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yellowtree/wp-geoip-detect/issues/18>.
>

-- 

Mit freundlichen Grüßen,

Benjamin Pick
Web-Entwickler

-----------------------------------------------------------------
YELLOW TREE
AGENTUR FÜR DESIGN UND KOMMUNIKATION
-----------------------------------------------------------------
T  +49 (0) 271 703019 - 5
F  +49 (0) 271 703019 - 8
B.PICK@YELLOWTREE.DE <mailto:B.PICK@YELLOWTREE.DE>
WWW.YELLOWTREE.DE
-----------------------------------------------------------------
SANDSTRASSE 173, 57072 SIEGEN
-----------------------------------------------------------------





Rafflenbeul und Utsch GbR
Rechtsform: Gesellschaft des bürgerlichen Rechts
Gesellschafter: 
Heiko Rafflenbeul und Andreas Utsch
Sitz der Gesellschaft: Siegen, Deutschland
Steuer-Nr.: 342 5827 0518
-----------------------------------------------------------------

Diese E-Mail enthaelt vertrauliche oder rechtlich
geschuetzte Informationen.Wenn Sie nicht der
beabsichtigte Empfaenger sind, informieren Sie
bitte sofort den Absender und loeschen Sie diese
E-Mail. Das unbefugte Kopieren dieser E-Mail oder
die unbefugte Weitergabe der enthaltenen
Informationen ist nicht gestattet.
 
The information contained in this message is
confidential or protected by law.If you are not the
intended recipient, please contact the sender and
delete this message. Any unauthorised copying
of this message or unauthorised distribution of the
information contained herein is prohibited.

**Comment by alaninteractive** [comment] 2015-07-15 23:29
Thanks Benjamin. I'd started developing a workaround using an Ajax lookup from http://freegeoip.net, so your suggestion sounds spot-on.

But I'm also working through this with WPEngine Support. There is the suggestion of doing the geo lookup from an include that is excluded from their cache, but that remains to be tested.

I'll let you know how I get on. Thanks again for the great plugin.

**Comment by benjaminpick** [comment] 2015-07-16 06:01
Thought about the AJAX solution some more. If somebody bought the commercial file database, or uses the Precision API Endpoint, it must not be used by other websites. But this is difficult to do: normally one would use nonces for this but this doesn't work if the HTML is cached. Any ideas?

**Comment by benjaminpick** [comment] 2018-07-20 15:15
Closing as duplicate of #19

**Closed by benjaminpick** 2018-07-20 15:15 UTC

**Comment by hexagongirl** [comment] 2018-10-22 10:06
@alaninteractive sorry to drag up an old issue, but I'm facing the same problem with WP Engine caching; did you ever solve this/do you remember how?

I've had WPE disable caching on the plugin directory (& also my mu-plugin which is calling `geoip_detect2_get_info_from_current_ip`) but to no avail.
